---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-upgrade-k8s-upgrade-operator-v1alpha1-kubernetesupgrade
  failurePolicy: Fail
  name: vkubernetesupgrade-v1alpha1.kb.io
  rules:
  - apiGroups:
    - upgrade.k8s-upgrade-operator
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubernetesupgrades
  sideEffects: None
