---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - upgrade.k8s-upgrade-operator
  resources:
  - kubernetesupgrades
  - nodegroupupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.k8s-upgrade-operator
  resources:
  - kubernetesupgrades/finalizers
  - nodegroupupgrades/finalizers
  verbs:
  - update
- apiGroups:
  - upgrade.k8s-upgrade-operator
  resources:
  - kubernetesupgrades/status
  - nodegroupupgrades/status
  verbs:
  - get
  - patch
  - update
