//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSAutoScalingGroupRef) DeepCopyInto(out *AWSAutoScalingGroupRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSAutoScalingGroupRef.
func (in *AWSAutoScalingGroupRef) DeepCopy() *AWSAutoScalingGroupRef {
	if in == nil {
		return nil
	}
	out := new(AWSAutoScalingGroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSEKSNodeGroupRef) DeepCopyInto(out *AWSEKSNodeGroupRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSEKSNodeGroupRef.
func (in *AWSEKSNodeGroupRef) DeepCopy() *AWSEKSNodeGroupRef {
	if in == nil {
		return nil
	}
	out := new(AWSEKSNodeGroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneUpgradeStatus) DeepCopyInto(out *ControlPlaneUpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneUpgradeStatus.
func (in *ControlPlaneUpgradeStatus) DeepCopy() *ControlPlaneUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredGroupStatus) DeepCopyInto(out *DiscoveredGroupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredGroupStatus.
func (in *DiscoveredGroupStatus) DeepCopy() *DiscoveredGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveredGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainPolicy) DeepCopyInto(out *DrainPolicy) {
	*out = *in
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.GracePeriodSeconds != nil {
		in, out := &in.GracePeriodSeconds, &out.GracePeriodSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainPolicy.
func (in *DrainPolicy) DeepCopy() *DrainPolicy {
	if in == nil {
		return nil
	}
	out := new(DrainPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesUpgrade) DeepCopyInto(out *KubernetesUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesUpgrade.
func (in *KubernetesUpgrade) DeepCopy() *KubernetesUpgrade {
	if in == nil {
		return nil
	}
	out := new(KubernetesUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesUpgradeList) DeepCopyInto(out *KubernetesUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubernetesUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesUpgradeList.
func (in *KubernetesUpgradeList) DeepCopy() *KubernetesUpgradeList {
	if in == nil {
		return nil
	}
	out := new(KubernetesUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesUpgradeSpec) DeepCopyInto(out *KubernetesUpgradeSpec) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(UpgradeScope)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(UpgradeDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupOverrides != nil {
		in, out := &in.GroupOverrides, &out.GroupOverrides
		*out = make([]NodeGroupOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Safety != nil {
		in, out := &in.Safety, &out.Safety
		*out = new(SafetyPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesUpgradeSpec.
func (in *KubernetesUpgradeSpec) DeepCopy() *KubernetesUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesUpgradeStatus) DeepCopyInto(out *KubernetesUpgradeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StepPlan != nil {
		in, out := &in.StepPlan, &out.StepPlan
		*out = make([]UpgradeStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ControlPlane = in.ControlPlane
	if in.DiscoveredGroups != nil {
		in, out := &in.DiscoveredGroups, &out.DiscoveredGroups
		*out = make([]DiscoveredGroupStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesUpgradeStatus.
func (in *KubernetesUpgradeStatus) DeepCopy() *KubernetesUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(KubernetesUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeLKEPoolRef) DeepCopyInto(out *LinodeLKEPoolRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeLKEPoolRef.
func (in *LinodeLKEPoolRef) DeepCopy() *LinodeLKEPoolRef {
	if in == nil {
		return nil
	}
	out := new(LinodeLKEPoolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupOverride) DeepCopyInto(out *NodeGroupOverride) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(NodeGroupStrategy)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(bool)
		**out = **in
	}
	if in.Skip != nil {
		in, out := &in.Skip, &out.Skip
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupOverride.
func (in *NodeGroupOverride) DeepCopy() *NodeGroupOverride {
	if in == nil {
		return nil
	}
	out := new(NodeGroupOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupUpgrade) DeepCopyInto(out *NodeGroupUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupUpgrade.
func (in *NodeGroupUpgrade) DeepCopy() *NodeGroupUpgrade {
	if in == nil {
		return nil
	}
	out := new(NodeGroupUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroupUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupUpgradeList) DeepCopyInto(out *NodeGroupUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeGroupUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupUpgradeList.
func (in *NodeGroupUpgradeList) DeepCopy() *NodeGroupUpgradeList {
	if in == nil {
		return nil
	}
	out := new(NodeGroupUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroupUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupUpgradeSpec) DeepCopyInto(out *NodeGroupUpgradeSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProviderRef != nil {
		in, out := &in.ProviderRef, &out.ProviderRef
		*out = new(ProviderRef)
		(*in).DeepCopyInto(*out)
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	in.Drain.DeepCopyInto(&out.Drain)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupUpgradeSpec.
func (in *NodeGroupUpgradeSpec) DeepCopy() *NodeGroupUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeGroupUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupUpgradeStatus) DeepCopyInto(out *NodeGroupUpgradeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeProgress != nil {
		in, out := &in.NodeProgress, &out.NodeProgress
		*out = make([]NodeProgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupUpgradeStatus.
func (in *NodeGroupUpgradeStatus) DeepCopy() *NodeGroupUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeGroupUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProgress) DeepCopyInto(out *NodeProgress) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProgress.
func (in *NodeProgress) DeepCopy() *NodeProgress {
	if in == nil {
		return nil
	}
	out := new(NodeProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRef) DeepCopyInto(out *ProviderRef) {
	*out = *in
	if in.AWSEKS != nil {
		in, out := &in.AWSEKS, &out.AWSEKS
		*out = new(AWSEKSNodeGroupRef)
		**out = **in
	}
	if in.AWSASG != nil {
		in, out := &in.AWSASG, &out.AWSASG
		*out = new(AWSAutoScalingGroupRef)
		**out = **in
	}
	if in.LinodeLKE != nil {
		in, out := &in.LinodeLKE, &out.LinodeLKE
		*out = new(LinodeLKEPoolRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRef.
func (in *ProviderRef) DeepCopy() *ProviderRef {
	if in == nil {
		return nil
	}
	out := new(ProviderRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyPolicy) DeepCopyInto(out *SafetyPolicy) {
	*out = *in
	if in.ControlPlaneHealthTimeoutSeconds != nil {
		in, out := &in.ControlPlaneHealthTimeoutSeconds, &out.ControlPlaneHealthTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyPolicy.
func (in *SafetyPolicy) DeepCopy() *SafetyPolicy {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeDefaults) DeepCopyInto(out *UpgradeDefaults) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.DrainTimeoutSeconds != nil {
		in, out := &in.DrainTimeoutSeconds, &out.DrainTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ForceDrainAfterTimeout != nil {
		in, out := &in.ForceDrainAfterTimeout, &out.ForceDrainAfterTimeout
		*out = new(bool)
		**out = **in
	}
	if in.NodeReadyTimeoutSeconds != nil {
		in, out := &in.NodeReadyTimeoutSeconds, &out.NodeReadyTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeDefaults.
func (in *UpgradeDefaults) DeepCopy() *UpgradeDefaults {
	if in == nil {
		return nil
	}
	out := new(UpgradeDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeScope) DeepCopyInto(out *UpgradeScope) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeScope.
func (in *UpgradeScope) DeepCopy() *UpgradeScope {
	if in == nil {
		return nil
	}
	out := new(UpgradeScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStep) DeepCopyInto(out *UpgradeStep) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStep.
func (in *UpgradeStep) DeepCopy() *UpgradeStep {
	if in == nil {
		return nil
	}
	out := new(UpgradeStep)
	in.DeepCopyInto(out)
	return out
}
